apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rpt-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{ .Values.rptIngress.hostName }}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: angular
            port:
              number: 80
      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: express
            port:
              number: 3000
      - path: /api-docs/(.*)
        pathType: Prefix
        backend:
          service:
            name: swagger
            port:
              number: 3000
  tls:
  - hosts:
    - {{ .Values.rptIngress.hostName }}
    secretName: {{ .Values.rptIngress.sslCertName }}
