apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rptMongo.serviceName }}
  labels:
    app: {{ .Values.rptMongo.resources.reqMemory }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.rptMongo.label }}
  ports:
    - port: {{ .Values.rptMongo.port }}
      targetPort: {{ .Values.rptMongo.targetPort }}